### ISSUE TITLE
Responsiv design, VueX, Router, refaktorering

### ISSUE THREAD

**Issue by synnesorensen** [HVL-12-2021/bachelor#106]
Etter brukertest viser det seg at kunder må scrolle en del for å se alt innholdet på en liten skjerm. Gjelder spesielt customer overview. 
Appen trenger også ellers å tilpasses små skjermer. Dette ble gjort sammen med refaktorering og tilpasning til kunder uten abo (#163 )

**Comment by torilapelthun** [comment]
Har ikke sett sånn kjempemye på det, men kom over dette: https://vuetifyjs.com/en/features/breakpoints/
