### ISSUE TITLE
La kunde sette abonnement på pause

### ISSUE THREAD

**Issue by synnesorensen** [HVL-12-2021/bachelor#80]
Bruk put på u/subscription (API putUserSubscription(subscription: interfaces.Subscription)) til å sette subscription.paused til true. 
Deretter må leveransene i kalenderen fjernes eller merkes med en annen farge.
Avhengig av #77

**Comment by ihjelle** [comment]
Bugs:
- Teksten på kansellerings-kanppen i customerProfile må endre seg i det man trykker, ikke etter refresh
- Dialogboksen i customerOveview for kansellering av levering må kun komme opp på leveringer som ikke er kansellert. 
- Fargen i kalenderen må oppdatere  seg i det bestillingen blir kansellert, ikke etter refresh
